package core

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeMeta(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".worktrees.json"), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestValidateBranchNameAllowsWhenUnset(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"symlink_candidates":[]}}`)
	if err := ValidateBranchName(dir, "feat/issue-163-8fb2c430"); err != nil {
		t.Fatalf("unset pattern must allow anything, got %v", err)
	}
}

func TestValidateBranchNameAllowsDefaultPattern(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":".*"}}`)
	if err := ValidateBranchName(dir, "anything/goes-here"); err != nil {
		t.Fatalf("default pattern must allow anything, got %v", err)
	}
}

func TestValidateBranchNameRejectsAutoGeneratedName(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":"issue[0-9]+_dsc[0-9]+(_[a-z0-9-]+)?"}}`)
	if err := ValidateBranchName(dir, "feat/issue-163-8fb2c430"); err == nil {
		t.Fatal("auto-generated name must be rejected under a strict pattern")
	}
	if err := ValidateBranchName(dir, "issue161_dsc12493"); err != nil {
		t.Fatalf("conforming name must pass, got %v", err)
	}
	if err := ValidateBranchName(dir, "issue137_dsc11949_restrict"); err != nil {
		t.Fatalf("conforming name with suffix must pass, got %v", err)
	}
}

// A substring match would accept these; full-string matching must not.
func TestValidateBranchNameAnchorsImplicitly(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":"issue[0-9]+_dsc[0-9]+"}}`)
	for _, name := range []string{"feat/issue161_dsc12493", "issue161_dsc12493-wip", "xissue161_dsc12493x"} {
		if err := ValidateBranchName(dir, name); err == nil {
			t.Fatalf("%q must be rejected by an implicitly anchored pattern", name)
		}
	}
}

func TestValidateBranchNameDoesNotDoubleAnchor(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":"^issue[0-9]+_dsc[0-9]+$"}}`)
	if err := ValidateBranchName(dir, "issue161_dsc12493"); err != nil {
		t.Fatalf("explicitly anchored pattern must behave the same, got %v", err)
	}
	if err := ValidateBranchName(dir, "issue161_dsc12493-wip"); err == nil {
		t.Fatal("explicitly anchored pattern must still reject a trailing suffix")
	}
}

// Alternation at the top level must not leak past the anchors: without the
// non-capturing group, "^a|b$" would accept anything containing "b".
func TestValidateBranchNameWrapsAlternation(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":"main|issue[0-9]+"}}`)
	if err := ValidateBranchName(dir, "issue12"); err != nil {
		t.Fatalf("alternation branch must pass, got %v", err)
	}
	if err := ValidateBranchName(dir, "feat/main-thing"); err == nil {
		t.Fatal("alternation must not match a substring")
	}
}

func TestValidateBranchNameRejectsInvalidPattern(t *testing.T) {
	dir := writeMeta(t, `{"_config":{"branch_pattern":"issue[0-9"}}`)
	err := ValidateBranchName(dir, "issue161_dsc12493")
	if err == nil {
		t.Fatal("an invalid pattern must fail closed, not allow everything")
	}
	if !strings.Contains(err.Error(), "正規表現として不正") {
		t.Fatalf("error must name the cause, got %v", err)
	}
}
